version: "3.3"
services:
  upbeat_db:
    image: postgres:14.2
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432" # expose pg on port 5632 to not collide with pg from elswhere
  # web:
  #   build:
  #     context: ./
  #     target: dev
  #   volumes:
  #     - .:/app
  #   ports:
  #     - "4000:4000"
  #   environment:
  #     - PORT=4000
  #   command: yarn dev

volumes:
  db-data:
    driver: local
